### ISSUE TITLE
It seems that configuration cache cannot be supported.

### ISSUE THREAD

**Issue by 5peak2me** [LikeTheSalad/android-stem#154]
```
5 problems were found storing the configuration cache, 4 of which seem unique.
- Task `:app:templateStringDebugResourceLocator` of type `com.likethesalad.tools.resource.locator.android.task.ResourceLocatorTask`: cannot serialize object of type 'org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer', a subtype of 'org.gradle.api.artifacts.ConfigurationContainer', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.10.1/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:app:templateStringDebugResourceLocator` of type `com.likethesalad.tools.resource.locator.android.task.ResourceLocatorTask`: cannot serialize object of type 'org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler', a subtype of 'org.gradle.api.artifacts.dsl.DependencyHandler', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.10.1/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:app:templateStringDebugResourceLocator` of type `com.likethesalad.tools.resource.locator.android.task.ResourceLocatorTask`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.10.1/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:app:templateStringDebugResourceLocator` of type `com.likethesalad.tools.resource.locator.android.task.ResourceLocatorTask`: cannot serialize object of type 'org.jetbrains.kotlin.gradle.internal.properties.PropertiesBuildService', a subtype of 'org.gradle.api.services.BuildService', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.10.1/userguide/configuration_cache.html#config_cache:requirements:disallowed_types

See the complete report at file:///Users/xxx/AndroidStudioProjects/xxx/build/reports/configuration-cache/9bkn32amxk47zxgc6ah39dshn/7nrl0sscijbuvlnv5wymxyzmo/configuration-cache-report.html

FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache state could not be cached: field `queue` of `java.util.WeakHashMap` bean found in field `values` of `org.jetbrains.kotlin.gradle.utils.StoredPropertyStorage` bean found in field `storage` of `org.gradle.internal.extensibility.DefaultExtraPropertiesExtension` bean found in field `extraProperties` of `com.android.build.gradle.internal.services.ProjectServices` bean found in field `projectServices` of `com.android.build.gradle.internal.services.VariantServicesImpl` bean found in field `variantServices` of `com.android.build.api.variant.impl.BundleConfigImpl` bean found in field `bundleConfig` of `com.android.build.api.variant.impl.ApplicationVariantImpl` bean found in field `variant` of `com.likethesalad.tools.agpcompat74.bridges.AndroidVariantData74` bean found in field `androidVariantData` of `com.likethesalad.tools.resource.collector.android.data.variant.VariantTree` bean found in field `variantTree` of `com.likethesalad.tools.resource.collector.android.AndroidResourceCollector` bean found in field `collector` of task `:app:templateStringDebugResourceLocator` of type `com.likethesalad.tools.resource.locator.android.task.ResourceLocatorTask`: error writing value of type 'java.lang.ref.ReferenceQueue'
> Unable to make field private volatile java.lang.ref.Reference java.lang.ref.ReferenceQueue.head accessible: module java.base does not "opens java.lang.ref" to unnamed module @7527cf37

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.internal.cc.impl.ConfigurationCacheError: Configuration cache state could not be cached: field `queue` of `java.util.WeakHashMap` bean found in field `values` of `org.jetbrains.kotlin.gradle.utils.StoredPropertyStorage` bean found in field `storage` of `org.gradle.internal.extensibility.DefaultExtraPropertiesExtension` bean found in field `extraProperties` of `com.android.build.gradle.internal.services.ProjectServices` bean found in field `projectServices` of `com.android.build.gradle.internal.services.VariantServicesImpl` bean found in field `variantServices` of `com.android.build.api.variant.impl.BundleConfigImpl` bean found in field `bundleConfig` of `com.android.build.api.variant.impl.ApplicationVariantImpl` bean found in field `variant` of `com.likethesalad.tools.agpcompat74.bridges.AndroidVariantData74` bean found in field `androidVariantData` of `com.likethesalad.tools.resource.collector.android.data.variant.VariantTree` bean found in field `variantTree` of `com.likethesalad.tools.resource.collector.android.AndroidResourceCollector` bean found in field `collector` of task `:app:templateStringDebugResourceLocator` of type `com.likethesalad.tools.resource.locator.android.task.ResourceLocatorTask`: error writing value of type 'java.lang.ref.ReferenceQueue'
	at org.gradle.internal.cc.impl.problems.AbstractProblemsListener.onError(AbstractProblemsListener.kt:36)
	at org.gradle.internal.serialize.graph.AbstractIsolateContext.onError(Contexts.kt:267)
	at org.gradle.internal.serialize.graph.BeanPropertyExtensionsKt.writeNextProperty(BeanPropertyExtensions.kt:36)
	at org.gradle.internal.serialize.graph.BeanPropertyExtensionsKt$writeNextProperty$1.invokeSuspend(BeanPropertyExtensions.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:41)
	at org.gradle.internal.serialize.graph.CombinatorsKt$reentrant$1$encodeLoop$$inlined$Continuation$1.resumeWith(Continuation.kt:168)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at org.gradle.internal.serialize.graph.CombinatorsKt$reentrant$1.encodeLoop(Combinators.kt:99)
	at org.gradle.internal.serialize.graph.CombinatorsKt$reentrant$1.encode(Combinators.kt:66)
	at org.gradle.internal.serialize.graph.codecs.BindingsBackedCodec.encode(BindingsBackedCodec.kt:62)
	at org.gradle.internal.serialize.graph.DefaultWriteContext.write(Contexts.kt:84)
	at org.gradle.internal.serialize.graph.BeanPropertyExtensionsKt.writeNextProperty(BeanPropertyExtensions.kt:34)
	at org.gradle.internal.serialize.beans.services.BeanPropertyWriter.writeStateOf(BeanPropertyWriter.kt:54)
	at org.gradle.internal.serialize.codecs.core.TaskNodeCodec$writeTask$3$2$1.invokeSuspend(TaskNodeCodec.kt:102)
	at org.gradle.internal.serialize.codecs.core.TaskNodeCodec$writeTask$3$2$1.invoke(TaskNodeCodec.kt)
	at org.gradle.internal.serialize.codecs.core.TaskNodeCodec$writeTask$3$2$1.invoke(TaskNodeCodec.kt)
	at org.gradle.internal.serialize.codecs.core.TaskNodeCodecKt.withTaskOf(TaskNodeCodec.kt:235)
	at org.gradle.internal.serialize.codecs.core.TaskNodeCodecKt.access$withTaskOf(TaskNodeCodec.kt:1)
	at org.gradle.internal.serialize.codecs.core.TaskNodeCodec.writeTask(TaskNodeCodec.kt:96)
	at org.gradle.internal.serialize.codecs.core.TaskNodeCodec.encode(TaskNodeCodec.kt:73)
	at org.gradle.internal.serialize.codecs.core.TaskNodeCodec.encode(TaskNodeCodec.kt:66)
	at org.gradle.internal.serialize.graph.codecs.BindingsBackedCodec.encode(BindingsBackedCodec.kt:62)
	at org.gradle.internal.serialize.graph.DefaultWriteContext.write(Contexts.kt:84)
	at org.gradle.internal.serialize.codecs.core.WorkNodeCodec.doWrite(WorkNodeCodec.kt:85)
	at org.gradle.internal.serialize.codecs.core.WorkNodeCodec.writeWork(WorkNodeCodec.kt:64)
	at org.gradle.internal.cc.impl.ConfigurationCacheState.writeWorkGraphOf(ConfigurationCacheState.kt:496)
	at org.gradle.internal.cc.impl.ConfigurationCacheState.writeBuildContent$configuration_cache(ConfigurationCacheState.kt:457)
	at org.gradle.internal.cc.impl.ConfigurationCacheState.writeBuildState(ConfigurationCacheState.kt:313)
	at org.gradle.internal.cc.impl.ConfigurationCacheState.writeBuildsInTree(ConfigurationCacheState.kt:287)
	at org.gradle.internal.cc.impl.ConfigurationCacheState.writeRootBuild(ConfigurationCacheState.kt:262)
	at org.gradle.internal.cc.impl.ConfigurationCacheState.writeRootBuildState(ConfigurationCacheState.kt:160)
	at org.gradle.internal.cc.impl.DefaultConfigurationCacheIO$writeRootBuildStateTo$1.invokeSuspend(DefaultConfigurationCacheIO.kt:173)
	at org.gradle.internal.cc.impl.DefaultConfigurationCacheIO$writeRootBuildStateTo$1.invoke(DefaultConfigurationCacheIO.kt)
	at org.gradle.internal.cc.impl.DefaultConfigurationCacheIO$writeRootBuildStateTo$1.invoke(DefaultConfigurationCacheIO.kt)
	at org.gradle.internal.cc.impl.DefaultConfigurationCacheIO$writeConfigurationCacheState$3$1.invokeSuspend(DefaultConfigurationCacheIO.kt:227)
	at org.gradle.internal.cc.impl.DefaultConfigurationCacheIO$writeConfigurationCacheState$3$1.invoke(DefaultConfigurationCacheIO.kt)
	at org.gradle.internal.cc.impl.DefaultConfigurationCacheIO$writeConfigurationCacheState$3$1.invoke(DefaultConfigurationCacheIO.kt)
	at org.gradle.internal.serialize.graph.RunningKt$runWriteOperation$1.invokeSuspend(Running.kt:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at org.gradle.internal.serialize.graph.RunningKt.runToCompletion(Running.kt:54)
	at org.gradle.internal.serialize.graph.RunningKt.runWriteOperation(Running.kt:42)
	at org.gradle.internal.cc.impl.DefaultConfigurationCacheIO.writeConfigurationCacheState(DefaultConfigurationCacheIO.kt:226)
	at org.gradle.internal.cc.impl.DefaultConfigurationCacheIO.writeRootBuildStateTo(DefaultConfigurationCacheIO.kt:171)
	at org.gradle.internal.cc.impl.DefaultConfigurationCache$writeConfigurationCacheState$1.run(DefaultConfigurationCache.kt:493)
	at org.gradle.internal.Factories$1.create(Factories.java:31)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withReplacedLocks(DefaultWorkerLeaseService.java:359)
	at org.gradle.api.internal.project.DefaultProjectStateRegistry$DefaultBuildProjectRegistry.withMutableStateOfAllProjects(DefaultProjectStateRegistry.java:238)
	at org.gradle.api.internal.project.DefaultProjectStateRegistry$DefaultBuildProjectRegistry.withMutableStateOfAllProjects(DefaultProjectStateRegistry.java:231)
	at org.gradle.internal.cc.impl.DefaultConfigurationCache.writeConfigurationCacheState(DefaultConfigurationCache.kt:492)
	at org.gradle.internal.cc.impl.DefaultConfigurationCache.access$writeConfigurationCacheState(DefaultConfigurationCache.kt:72)
	at org.gradle.internal.cc.impl.DefaultConfigurationCache$saveWorkGraph$1.invoke(DefaultConfigurationCache.kt:418)
	at org.gradle.internal.cc.impl.DefaultConfigurationCache$saveWorkGraph$1.invoke(DefaultConfigurationCache.kt:416)
	at org.gradle.internal.cc.impl.DefaultConfigurationCache$saveToCache$1$1.invoke(DefaultConfigurationCache.kt:434)
	at org.gradle.internal.cc.impl.DefaultConfigurationCache$saveToCache$1$1.invoke(DefaultConfigurationCache.kt:431)
	at org.gradle.internal.cc.impl.ConfigurationCacheRepository$StoreImpl$useForStore$1.invoke(ConfigurationCacheRepository.kt:189)
	at org.gradle.internal.cc.impl.ConfigurationCacheRepository$StoreImpl$useForStore$1.invoke(ConfigurationCacheRepository.kt:181)
	at org.gradle.internal.cc.impl.ConfigurationCacheRepository$withExclusiveAccessToCache$1.get(ConfigurationCacheRepository.kt:251)
	at org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess.withFileLock(LockOnDemandCrossProcessCacheAccess.java:90)
	at org.gradle.cache.internal.DefaultCacheCoordinator.withFileLock(DefaultCacheCoordinator.java:213)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.withFileLock(DefaultPersistentDirectoryStore.java:149)
	at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.withFileLock(DefaultCacheFactory.java:206)
	at org.gradle.internal.cc.impl.ConfigurationCacheRepository.withExclusiveAccessToCache(ConfigurationCacheRepository.kt:249)
	at org.gradle.internal.cc.impl.ConfigurationCacheRepository.access$withExclusiveAccessToCache(ConfigurationCacheRepository.kt:48)
	at org.gradle.internal.cc.impl.ConfigurationCacheRepository$StoreImpl.useForStore(ConfigurationCacheRepository.kt:181)
	at org.gradle.internal.cc.impl.DefaultConfigurationCache$saveToCache$1.invoke(DefaultConfigurationCache.kt:431)
	at org.gradle.internal.cc.impl.DefaultConfigurationCache$saveToCache$1.invoke(DefaultConfigurationCache.kt:430)
	at org.gradle.configurationcache.ConfigurationCacheBuildOperationsKt$withStoreOperation$1.run(ConfigurationCacheBuildOperations.kt:62)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.configurationcache.ConfigurationCacheBuildOperationsKt.withStoreOperation(ConfigurationCacheBuildOperations.kt:55)
	at org.gradle.internal.cc.impl.DefaultConfigurationCache.saveToCache(DefaultConfigurationCache.kt:430)
	at org.gradle.internal.cc.impl.DefaultConfigurationCache.saveWorkGraph(DefaultConfigurationCache.kt:416)
	at org.gradle.internal.cc.impl.DefaultConfigurationCache.access$saveWorkGraph(DefaultConfigurationCache.kt:72)
	at org.gradle.internal.cc.impl.DefaultConfigurationCache$loadOrScheduleRequestedTasks$1.invoke(DefaultConfigurationCache.kt:173)
	at org.gradle.internal.cc.impl.DefaultConfigurationCache$loadOrScheduleRequestedTasks$1.invoke(DefaultConfigurationCache.kt:171)
	at org.gradle.internal.cc.impl.DefaultConfigurationCache.runWorkThatContributesToCacheEntry(DefaultConfigurationCache.kt:388)
	at org.gradle.internal.cc.impl.DefaultConfigurationCache.loadOrScheduleRequestedTasks(DefaultConfigurationCache.kt:171)
	at org.gradle.internal.cc.impl.ConfigurationCacheAwareBuildTreeWorkController$scheduleAndRunRequestedTasks$executionResult$1.apply(ConfigurationCacheAwareBuildTreeWorkController.kt:45)
	at org.gradle.internal.cc.impl.ConfigurationCacheAwareBuildTreeWorkController$scheduleAndRunRequestedTasks$executionResult$1.apply(ConfigurationCacheAwareBuildTreeWorkController.kt:44)
	at org.gradle.composite.internal.DefaultIncludedBuildTaskGraph.withNewWorkGraph(DefaultIncludedBuildTaskGraph.java:112)
	at org.gradle.internal.cc.impl.ConfigurationCacheAwareBuildTreeWorkController.scheduleAndRunRequestedTasks(ConfigurationCacheAwareBuildTreeWorkController.kt:44)
	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.lambda$scheduleAndRunTasks$1(DefaultBuildTreeLifecycleController.java:77)
	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.lambda$runBuild$4(DefaultBuildTreeLifecycleController.java:120)
	at org.gradle.internal.model.StateTransitionController.lambda$transition$6(StateTransitionController.java:169)
	at org.gradle.internal.model.StateTransitionController.doTransition(StateTransitionController.java:266)
	at org.gradle.internal.model.StateTransitionController.lambda$transition$7(StateTransitionController.java:169)
	at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:44)
	at org.gradle.internal.model.StateTransitionController.transition(StateTransitionController.java:169)
	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.runBuild(DefaultBuildTreeLifecycleController.java:117)
	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.scheduleAndRunTasks(DefaultBuildTreeLifecycleController.java:77)
	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.scheduleAndRunTasks(DefaultBuildTreeLifecycleController.java:72)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:53)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.internal.buildtree.ProblemReportingBuildActionRunner.run(ProblemReportingBuildActionRunner.java:49)
	at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:65)
	at org.gradle.tooling.internal.provider.FileSystemWatchingBuildActionRunner.run(FileSystemWatchingBuildActionRunner.java:140)
	at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:41)
	at org.gradle.launcher.exec.RootBuildLifecycleBuildActionExecutor.lambda$execute$0(RootBuildLifecycleBuildActionExecutor.java:54)
	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:130)
	at org.gradle.launcher.exec.RootBuildLifecycleBuildActionExecutor.execute(RootBuildLifecycleBuildActionExecutor.java:54)
	at org.gradle.internal.buildtree.InitDeprecationLoggingActionExecutor.execute(InitDeprecationLoggingActionExecutor.java:62)
	at org.gradle.internal.buildtree.InitProblems.execute(InitProblems.java:36)
	at org.gradle.internal.buildtree.DefaultBuildTreeContext.execute(DefaultBuildTreeContext.java:40)
	at org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor.lambda$execute$0(BuildTreeLifecycleBuildActionExecutor.java:71)
	at org.gradle.internal.buildtree.BuildTreeState.run(BuildTreeState.java:60)
	at org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor.execute(BuildTreeLifecycleBuildActionExecutor.java:71)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$3.call(RunAsBuildOperationBuildActionExecutor.java:61)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$3.call(RunAsBuildOperationBuildActionExecutor.java:57)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor.execute(RunAsBuildOperationBuildActionExecutor.java:57)
	at org.gradle.launcher.exec.RunAsWorkerThreadBuildActionExecutor.lambda$execute$0(RunAsWorkerThreadBuildActionExecutor.java:36)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:263)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:127)
	at org.gradle.launcher.exec.RunAsWorkerThreadBuildActionExecutor.execute(RunAsWorkerThreadBuildActionExecutor.java:36)
	at org.gradle.tooling.internal.provider.continuous.ContinuousBuildActionExecutor.execute(ContinuousBuildActionExecutor.java:110)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecutor.execute(SubscribableBuildActionExecutor.java:64)
	at org.gradle.internal.session.DefaultBuildSessionContext.execute(DefaultBuildSessionContext.java:46)
	at org.gradle.internal.buildprocess.execution.BuildSessionLifecycleBuildActionExecutor$ActionImpl.apply(BuildSessionLifecycleBuildActionExecutor.java:92)
	at org.gradle.internal.buildprocess.execution.BuildSessionLifecycleBuildActionExecutor$ActionImpl.apply(BuildSessionLifecycleBuildActionExecutor.java:80)
	at org.gradle.internal.session.BuildSessionState.run(BuildSessionState.java:71)
	at org.gradle.internal.buildprocess.execution.BuildSessionLifecycleBuildActionExecutor.execute(BuildSessionLifecycleBuildActionExecutor.java:62)
	at org.gradle.internal.buildprocess.execution.BuildSessionLifecycleBuildActionExecutor.execute(BuildSessionLifecycleBuildActionExecutor.java:41)
	at org.gradle.internal.buildprocess.execution.StartParamsValidatingActionExecutor.execute(StartParamsValidatingActionExecutor.java:64)
	at org.gradle.internal.buildprocess.execution.StartParamsValidatingActionExecutor.execute(StartParamsValidatingActionExecutor.java:32)
	at org.gradle.internal.buildprocess.execution.SessionFailureReportingActionExecutor.execute(SessionFailureReportingActionExecutor.java:51)
	at org.gradle.internal.buildprocess.execution.SessionFailureReportingActionExecutor.execute(SessionFailureReportingActionExecutor.java:39)
	at org.gradle.internal.buildprocess.execution.SetupLoggingActionExecutor.execute(SetupLoggingActionExecutor.java:47)
	at org.gradle.internal.buildprocess.execution.SetupLoggingActionExecutor.execute(SetupLoggingActionExecutor.java:31)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:70)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.lambda$execute$0(ForwardClientInput.java:40)
	at org.gradle.internal.daemon.clientinput.ClientInputForwarder.forwardInput(ClientInputForwarder.java:80)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:64)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:84)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator.lambda$runCommand$0(DaemonStateCoordinator.java:321)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:48)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private volatile java.lang.ref.Reference java.lang.ref.ReferenceQueue.head accessible: module java.base does not "opens java.lang.ref" to unnamed module @7527cf37
	at org.gradle.internal.serialize.beans.services.BeanSchemaKt.makeAccessible(BeanSchema.kt:179)
	at org.gradle.internal.serialize.beans.services.BeanSchemaKt$relevantFieldsOf$2.invoke(BeanSchema.kt:51)
	at org.gradle.internal.serialize.beans.services.BeanSchemaKt$relevantFieldsOf$2.invoke(BeanSchema.kt:51)
	at kotlin.sequences.SequencesKt___SequencesKt$onEach$1.invoke(_Sequences.kt:2171)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:811)
	at org.gradle.internal.serialize.beans.services.BeanSchemaKt.relevantFieldsOf(BeanSchema.kt:53)
	at org.gradle.internal.serialize.beans.services.BeanSchemaKt.relevantStateOf(BeanSchema.kt:43)
	at org.gradle.internal.serialize.beans.services.BeanPropertyWriter.<init>(BeanPropertyWriter.kt:36)
	at org.gradle.internal.serialize.beans.services.DefaultBeanStateWriterLookup$beanStateWriterFor$1.apply(DefaultBeanStateWriterLookup.kt:32)
	at org.gradle.internal.serialize.beans.services.DefaultBeanStateWriterLookup$beanStateWriterFor$1.apply(DefaultBeanStateWriterLookup.kt:32)
	at org.gradle.internal.serialize.beans.services.DefaultBeanStateWriterLookup.beanStateWriterFor(DefaultBeanStateWriterLookup.kt:32)
	at org.gradle.internal.serialize.graph.DefaultWriteContext.beanStateWriterFor(Contexts.kt:77)
	at org.gradle.internal.serialize.graph.codecs.BeanCodec.writeBeanOf(BeanCodec.kt:56)
	at org.gradle.internal.serialize.graph.codecs.BeanCodec.encode(BeanCodec.kt:35)
	at org.gradle.internal.serialize.graph.CombinatorsKt$reentrant$1$encodeLoop$1.invokeSuspend(Combinators.kt:97)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	... 159 more


BUILD FAILED in 1s
Configuration cache entry discarded with 5 problems.

```

**Comment by LikeTheSalad** [comment]
Thank you for letting me know about this issue, I'll have a look.

**Comment by LikeTheSalad** [comment]
This should be sorted on version `3.0.0`. Tough please feel free to reopen it if needed.
