### ISSUE TITLE
Illegal escape character on Windows path

### ISSUE THREAD

**Issue by dodos90** [LikeTheSalad/android-stem#24]
Hi @LikeTheSalad (again 😄 ),

As a follow-up to my previous issue, I have been able to successfully add the plugin to my project.
However, when building my app, the plugin fails with the following error : 

`Caused by: java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 4
^C:\Users\MY_USERNAME\Projects\android-sample-project.+
    ^
	at kotlin.text.Regex.<init>(Regex.kt:89)
	at com.likethesalad.stem.locator.entrypoints.common.source.configuration.TemplateProvidersResourceSourceConfiguration.filterLocalJars(TemplateProvidersResourceSourceConfiguration.kt:91)
	at com.likethesalad.stem.locator.entrypoints.common.source.configuration.TemplateProvidersResourceSourceConfiguration.createTemplatesProviderPathStartPattern(TemplateProvidersResourceSourceConfiguration.kt:63)
	at com.likethesalad.stem.locator.entrypoints.common.source.configuration.TemplateProvidersResourceSourceConfiguration.filterTemplateProviderResDirs(TemplateProvidersResourceSourceConfiguration.kt:48)
	at com.likethesalad.stem.locator.entrypoints.common.source.configuration.TemplateProvidersResourceSourceConfiguration.getResDirs(TemplateProvidersResourceSourceConfiguration.kt:40)
	at com.likethesalad.tools.resource.locator.android.extension.configuration.source.base.ResDirResourceSourceConfiguration.doGetSourceProviders(ResDirResourceSourceConfiguration.kt:16)
	at com.likethesalad.tools.resource.locator.android.extension.configuration.source.ResourceSourceConfiguration.getSourceProviders(ResourceSourceConfiguration.kt:16)
	at com.likethesalad.tools.resource.locator.android.task.ResourceLocatorTask.addResourceSources(ResourceLocatorTask.kt:80)`

I'm on a Windows computer (Windows 11, if that matters), and I guess that the `\` path separator messes up with your plugin Regex mechanism...
Let me know if there is a way to bypass this, or if I should wait for a fix on your side.

Thanks again for your help, I appreciate it !

**Comment by LikeTheSalad** [comment]
Hi @dodos90 !

No worries, this is a great opportunity for me because I didn't get the chance to check how this plugin works on a Windows machine before. I don't see a way for you to bypass it, but it seems like an easy fix so I think I should be able to provide a patch later today.

**Comment by LikeTheSalad** [comment]
Hi @dodos90 , the new version 2.1.1 is now available :+1: you should no longer see this issue with it, though please feel free to reopen this ticket otherwise.

Cheers!

**Comment by dodos90** [comment]
Thank you so much, everything works perfectly now ❤️

**Comment by LikeTheSalad** [comment]
That's great news @dodos90 ! glad to help, and many thanks for your support! :pray: :heart:
